/* tslint:disable */
/* eslint-disable */
/**
 * KotiKota
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {} from '.';

/**
 *
 *
 * @export
 * @interface Money
 */
export interface Money {
  /**
   * @type {number}
   * @memberof Money
   */
  amount?: number;
}
