/* tslint:disable */
/* eslint-disable */
/**
 * KotiKota
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Exception } from './exception';
import { Exception } from '.';

/**
 *
 *
 * @export
 * @interface TooManyRequestsException
 */
export interface TooManyRequestsException extends Exception {}
