/* tslint:disable */
/* eslint-disable */
/**
 * KotiKota
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: latest
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {} from '.';

/**
 *
 *
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
  /**
   * @type {string}
   * @memberof UserProfile
   */
  firstName?: string;

  /**
   * @type {string}
   * @memberof UserProfile
   */
  lastName?: string;

  /**
   * @type {string}
   * @memberof UserProfile
   */
  email?: string;
}
