import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "./common/components";

export const metadata: Metadata = {
  title: "Kokikota",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>{children}</SessionProvider>
      </body>
    </html>
  );
}
