import type { Metadata } from 'next';
import { MainProvider } from './common/components';
import './globals.css';

export const metadata: Metadata = {
  title: 'Kokikota',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
